### ISSUE TITLE
ADPCM4 (AFC)

### ISSUE THREAD

**Issue by SY-24** [XAYRGA/jatast#1]
Hello,

the program works like a charm. I noticed that it also supports ADPCM4 (AFC) encoding, although it creates some noise over the intended audio (sounds like someone blowing into a mike). Do you think you can fix/enhance that?

Would be greatly appreciated!

**Comment by XAYRGA** [comment]
Hi there, 

I'm working on this. While i've fixed the very bad crackles in the branch jatast2, i haven't yet fixed the transitions for the BLCK's.  

I need to do more research into how it works.

**Comment by XAYRGA** [comment]
Well, that took 11 minutes. fixed by [97217c3](https://github.com/XAYRGA/jatast/commit/97217c38e73e2bfc3d7fc0b172e7e743a027f8dd)

**Comment by SY-24** [comment]
Thanks for the fast reply,

I tried it and it works pretty good. No more clicks or distortion sounds. And the encoding works pretty fast as well!

Although I stumbled across one other issue. When trying to set custom loop points with the [--loop] command, the startSample gets set correctly, but the endSample doesn't for some reason. Using such an encoded file ingame (SMG2 in my case) the music plays once completely and then cuts off, no looping whatsoever.

So if I edit the endSample in a hex-editor and put the file into my game, the game crashes at JAISound related functions. Tried 32000 and 44100 Hz.

SMG2 usually has no problems with adpcm encoded AST files. I tested it with files from Twilight Princess and DK Jungle Beat without issues.

I attached the files that I tested your program with. One is encoded with adpcm4, the other with pcm16, but both were told to have the same startSample (76766) and endSample (691166) and both cut off ingame after playing once.

[SM64-FileSelect.zip](https://github.com/XAYRGA/jatast/files/9459078/SM64-FileSelect.zip)

It would be awesome if you could look into that issue specifically. Thanks again for the fast reply.
